CMake: allows to build the documentation as part of our CD action (#2573).

diff --git a/cd b/cd
--- a/cd
+++ b/cd
@@ -1,9 +1,53 @@
 #!/bin/sh
 
-cd build
+appDir=$(cd $(dirname $0); pwd)
 
-git clone --depth=1 https://github.com/opencor/opencor-user-documentation
+if [ -d $appDir/build ]; then
+    if [ "`hash ninja 2>&1`" = "" ]; then
+        ninjaFound=true
+        generator="Ninja"
+        cmakeGenerator="Ninja"
+    else
+        ninjaFound=false
+        generator="Make"
+        cmakeGenerator="Unix Makefiles"
+    fi
 
-cd opencor-user-documentation
+    echo "\033[44;37;1mGenerating OpenCOR's documentation using $generator...\033[0m"
 
-./opencor
+    origDir=`pwd`
+
+    cd $appDir/build
+
+    cmake -G "$cmakeGenerator" ../doc
+
+    exitCode=$?
+
+    if [ $exitCode -ne 0 ]; then
+        cd $origDir
+
+        exit $exitCode
+    fi
+
+    shift
+
+    if [ $ninjaFound = true ]; then
+        ninja $@
+    else
+        make $@
+    fi
+
+    exitCode=$?
+
+    cd $origDir
+
+    if [ $exitCode -eq 0 ]; then
+        echo "\033[42;37;1mAll done!\033[0m"
+    fi
+
+    exit $exitCode
+else
+    echo "OpenCOR's build directory is missing."
+
+    exit 1
+fi
